/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/main/Desktop/3143-game/src/assets/countries/ALBANIA.glb -o /Users/main/Desktop/3143-game/src/components/ALBANIA.jsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
    const { nodes, materials } = useGLTF('src/assets/countries/ALBANIA/ALBANIA.glb')
    return (
      <group {...props} dispose={null}>
        <group
          rotation={[Math.PI / 2, Math.PI, Math.PI]}
        >
          <mesh geometry={nodes.Curve.geometry} material={materials.SVGMat}>
            <meshStandardMaterial
              roughness={0.10}
              metalness={0.25}
              color={'black'}
            />
          </mesh>
        </group>
      </group>
    )
}
  
 useGLTF.preload('src/assets/countries/ALBANIA/ALBANIA.glb')
