/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/main/Desktop/3143-game/src/assets/countries/Armenia.glb -o /Users/main/Desktop/3143-game/src/components/Armenia.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Armenia(props) {
  const { nodes, materials } = useGLTF('src/assets/countries/Armenia/Armenia.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} />
    </group>
  )
}

useGLTF.preload('src/assets/countries/Armenia/Armenia.glb')
