

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VaticanCity(props) {
  const { nodes, materials } = useGLTF('src/assets/countries/VaticanCity/VaticanCity.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.020"]}
      />
    </group>
  );
}

useGLTF.preload('src/assets/countries/VaticanCity/VaticanCity.glb');