/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/main/Desktop/3143-game/src/assets/countries/Vanuatu.glb -o /Users/main/Desktop/3143-game/src/components/Vanuatu.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('src/assets/countries/Vanuatu/Vanuatu.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve005.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve006.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve007.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve008.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve009.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve010.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve011.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve012.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve013.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve014.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve015.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve016.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve017.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve018.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve019.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve020.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve021.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve022.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve023.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve024.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve025.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve026.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Curve027.geometry} material={materials['SVGMat.019']} />
    </group>
  )
}

useGLTF.preload('src/assets/countries/Vanuatu/Vanuatu.glb')
