/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/main/Desktop/3143-game/src/assets/countries/Chile.glb -o /Users/main/Desktop/3143-game/src/components/Chile.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chile.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve005.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve006.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve007.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve008.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve009.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve010.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve011.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve012.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve013.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve014.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve015.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve016.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve017.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve018.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve019.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve020.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve021.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve022.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve023.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve024.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve025.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve026.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve027.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve028.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve029.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve030.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve031.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve032.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve033.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve034.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve035.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve036.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve037.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve038.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve039.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve040.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve041.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve042.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve043.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve044.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve045.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve046.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve047.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve048.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve049.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve050.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve051.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve052.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve053.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve054.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve055.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve056.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve057.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve058.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve059.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve060.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve061.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve062.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve063.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve064.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve065.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve066.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve067.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve068.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve069.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve070.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve071.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve072.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve073.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve074.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve075.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve076.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve077.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve078.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve079.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve080.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve081.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve082.geometry} material={materials['SVGMat.046']} />
      <mesh geometry={nodes.Curve083.geometry} material={materials['SVGMat.046']} />
    </group>
  )
}

useGLTF.preload('/Chile.glb')
