/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/main/Desktop/3143-game/src/assets/countries/ALGERIA.glb -o /Users/main/Desktop/3143-game/src/components/ALGERIA.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Algeria(props) {
  const { nodes, materials } = useGLTF('src/assets/countries/Algeria/ALGERIA.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} />
    </group>
  )
}

useGLTF.preload('src/assets/countries/Algeria/ALGERIA.glb')
