/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/main/Desktop/3143-game/Argentina.glb -o /Users/main/Desktop/3143-game/src/components/Argentina.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Argentina(props) {
  const { nodes, materials } = useGLTF('Argentina.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={materials.SVGMat} material-roughness={0.10} material-metalness={0.80} material-color="grey" />
      <mesh geometry={nodes.Curve002.geometry} material={materials.SVGMat} material-roughness={0.10} material-metalness={0.80} material-color="grey" />
      <mesh geometry={nodes.Curve003.geometry} material={materials.SVGMat} material-roughness={0.10} material-metalness={0.80} material-color="grey" />
      <mesh geometry={nodes.Curve004.geometry} material={materials.SVGMat} material-roughness={0.10} material-metalness={0.80} material-color="grey" />
      <mesh geometry={nodes.Curve005.geometry} material={materials.SVGMat} material-roughness={0.10} material-metalness={0.80} material-color="grey" />
    </group>
  )
}

useGLTF.preload('Argentina.glb')
